import 'package:get/get.dart';

class ParkingSlotController extends GetxController {
  final slotData = <Map<String, dynamic>>[
    {"id": "Bonus", "slot": "Slot - 2", "occupied": true},
    {"id": "A1", "slot": "Slot - 1", "occupied": false},
    {"id": "A1", "slot": "Slot - 2", "occupied": false},
    {"id": "A1", "slot": "Slot - 3", "occupied": true},
    {"id": "A1", "slot": "Slot - 4", "occupied": false},
    {"id": "A1", "slot": "Slot - 5", "occupied": false},
    {"id": "A1", "slot": "Slot - 6", "occupied": true},
    {"id": "A1", "slot": "Slot - 7", "occupied": false},
    {"id": "A1", "slot": "Slot - 8", "occupied": false},
    {"id": "A1", "slot": "Slot - 9", "occupied": true},
    {"id": "A1", "slot": "Slot - 10", "occupied": false},
    {"id": "A1", "slot": "Slot - 11", "occupied": false},
    {"id": "A1", "slot": "Slot - 12", "occupied": true},
    {"id": "A1", "slot": "Slot - 13", "occupied": false},
    {"id": "A1", "slot": "Slot - 14", "occupied": false},
    {"id": "A1", "slot": "Slot - 15", "occupied": true},

    // A2 punya Slot 1–15
    {"id": "A2", "slot": "Slot - 1", "occupied": false},
    {"id": "A2", "slot": "Slot - 2", "occupied": true},
    {"id": "A2", "slot": "Slot - 3", "occupied": false},
    {"id": "A2", "slot": "Slot - 4", "occupied": false},
    {"id": "A2", "slot": "Slot - 5", "occupied": true},
    {"id": "A2", "slot": "Slot - 6", "occupied": false},
    {"id": "A2", "slot": "Slot - 7", "occupied": false},
    {"id": "A2", "slot": "Slot - 8", "occupied": true},
    {"id": "A2", "slot": "Slot - 9", "occupied": false},
    {"id": "A2", "slot": "Slot - 10", "occupied": true},
    {"id": "A2", "slot": "Slot - 11", "occupied": false},
    {"id": "A2", "slot": "Slot - 12", "occupied": false},
    {"id": "A2", "slot": "Slot - 13", "occupied": true},
    {"id": "A2", "slot": "Slot - 14", "occupied": false},
    {"id": "A2", "slot": "Slot - 15", "occupied": false},
    {"id": "B1", "slot": "Slot - 9", "occupied": true},
    {"id": "B2", "slot": "Slot - 2", "occupied": false},
    {"id": "B2", "slot": "Slot - 5", "occupied": false},
    {"id": "B2", "slot": "Slot - 6", "occupied": true},
    {"id": "C1", "slot": "Slot - 3", "occupied": true},
    {"id": "C2", "slot": "Slot - 3", "occupied": false},
    {"id": "D1", "slot": "Slot - 4", "occupied": false},
    {"id": "D2", "slot": "Slot - 4", "occupied": true},
    {"id": "E1", "slot": "Slot - 5", "occupied": false},
    {"id": "E2", "slot": "Slot - 5", "occupied": true},
    {"id": "F1", "slot": "Slot - 6", "occupied": true},
    {"id": "F2", "slot": "Slot - 6", "occupied": false},
  ].obs;
}
